#MySQL 5.7 Dev
version: '3.1'
services:
    mysql57:
    image: mysql:5.7
    hostname: mysql57
    container_name: mysql57-container
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3357:3306
    volumes:
      - /repos/docker/shared/mysql/mysql57-data:/var/lib/mysql
volumes:
  redis_data:
    driver: local      