# Rabbit MQ Server Dev
version: '3.1'

services:

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq-container
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672
volumes:
  redis_data:
    driver: local      