# Redis Server dev
version: '3.1'

services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis-container
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      # REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - '/repos/docker/shared/redis/data:/bitnami/redis/data'
volumes:
  redis_data:
    driver: local      