# Use root/example as user/password credentials
version: '3.1'

services:

  mysql8:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    hostname: mysql8
    container_name: mysql8-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3358:3306
    volumes:
      - E:\Docker\shared\mysql8:/var/lib/mysql

  mysql57:
    image: mysql:5.7
    restart: unless-stopped
    hostname: mysql57
    container_name: mysql57-container
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3357:3306
    volumes:
      - E:\Docker\shared\mysql7:/var/lib/mysql
    
  mysql56:
    image: mysql:5.6
    restart: unless-stopped
    hostname: mysql56
    container_name: mysql56-container
    environment:
      - MYSQL_ROOT_PASSWORD-root
    ports: 
      - 3356:3306
    volumes:
      - E:\Docker\shared\mysql6:/var/lib/mysql
